name: CICD Lambda Deploy

on:
  push:
    branches:
      - main
    paths:
      - deploy/** # Trigger only when files in the deploy folder change
    paths-ignore:
      - .github/**
      - document/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Step 2: Set up AWS credentials using GitHub Secrets
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Use your desired region

    # Step 3: Get the changed files
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v33

    # Step 4: Deploy CloudFormation stack for each changed file in deploy folder
    - name: Deploy CloudFormation stack
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          if [[ $file == deploy/*.yaml ]]; then
            stack_name=$(basename $file .yaml)
            echo "Deploying stack: $stack_name"
            aws cloudformation deploy \
              --template-file $file \
              --stack-name $stack_name \
              --capabilities CAPABILITY_NAMED_IAM
          else
            echo "No CloudFormation template changes detected."
          fi
        done
